### ISSUE TITLE
Unable to Import, Please help.

### ISSUE THREAD

**Issue by rhythm98** [gurleensethi/JKioskLibrary#3]
Failed to resolve: com.github.gurleensethi:JKioskLibrary:v1.0.0
Show in Project Structure dialog
Affected Modules: app

**Comment by gurleensethi** [comment]
Hi @rhythm98 

I am not maintaining this repository anymore.

You can either fix the issue and give a pull request. Contributions are always welcome 😃.

Or

You can grab the code directly that implements fetching data from Webkiosk, modify it according to your needs and use it in your project.

Regards,
Gurleen Sethi

**Comment by rhythm98** [comment]
Thanks
